In [20]:
import pandas as pd
import scipy.stats as stats
import numpy as np

In [3]:
countries = pd.read_csv("CountriesSD.csv")
summer = pd.read_csv("SummerSD.csv")
winter = pd.read_csv("WinterSD.csv")

In [4]:
countries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      201 non-null    int64
 1   Country         201 non-null    object
 2   Code            201 non-null    object
 3   Population      196 non-null    float64
 4   GDP per Capita  176 non-null    float64
dtypes: float64(2), int64(1), object(2)
memory usage: 8.0+ KB

In [12]:
#clean any missing values from each dataset
clean_countries = countries.dropna()

In [11]:
#clean any missing values from each dataset
clean_summer = summer.dropna()

In [10]:
clean_winter = winter.dropna()

In [13]:
clean_summer.head(5)

,Unnamed: 0,Year,City,Sport,Discipline,Athlete,Code,Gender,Event,Medal,Country
0,0,1896,Athens,Aquatics,Swimming,Alfred Hajos,HUN,Men,100M Freestyle,Gold,Hungary
1,1,1896,Athens,Aquatics,Swimming,Otto Herschmann,AUT,Men,100M Freestyle,Silver,Austria
2,2,1896,Athens,Aquatics,Swimming,Dimitrios Drivas,GRE,Men,100M Freestyle For Sailors,Bronze,Greece
3,3,1896,Athens,Aquatics,Swimming,Ioannis Malokinis,GRE,Men,100M Freestyle For Sailors,Gold,Greece
4,4,1896,Athens,Aquatics,Swimming,Spiridon Chasapis,GRE,Men,100M Freestyle For Sailors,Silver,Greece

In [14]:
clean_countries.head(5)

   Unnamed: 0              Country Code  Population  GDP per Capita
0           0          Afghanistan  AFG  32526562.0      594.323081
1           1              Albania  ALB   2889167.0     3945.217582
2           2              Algeria  ALG  39666519.0     4206.031232
5           5               Angola  ANG  25021974.0     4101.472152
6           6  Antigua and Barbuda  ANT     91818.0    13714.731962

In [ ]:
# joining the clean version of summer to clean version of countries - one to many
join_sum_countries = clean_summer.merge(clean_countries, on="Country", how="left")

In [16]:
join_sum_countries.head()

,Unnamed: 0_x,Year,City,Sport,Discipline,Athlete,Code_x,Gender,Event,Medal,Country,Unnamed: 0_y,Code_y,Population,GDP per Capita
0,0,1896,Athens,Aquatics,Swimming,Alfred Hajos,HUN,Men,100M Freestyle,Gold,Hungary,82.0,HUN,9844686.0,12363.543460
1,1,1896,Athens,Aquatics,Swimming,Otto Herschmann,AUT,Men,100M Freestyle,Silver,Austria,11.0,AUT,8611088.0,43774.985174
2,2,1896,Athens,Aquatics,Swimming,Dimitrios Drivas,GRE,Men,100M Freestyle For Sailors,Bronze,Greece,72.0,GRE,10823732.0,18002.230578
3,3,1896,Athens,Aquatics,Swimming,Ioannis Malokinis,GRE,Men,100M Freestyle For Sailors,Gold,Greece,72.0,GRE,10823732.0,18002.230578
4,4,1896,Athens,Aquatics,Swimming,Spiridon Chasapis,GRE,Men,100M Freestyle For Sailors,Silver,Greece,72.0,GRE,10823732.0,18002.230578

In [ ]:
# taking out unnecesary / repeat colums
join_sum_countries = join_sum_countries.drop(columns=["Unnamed: 0_x", "Unnamed: 0_y", "Code_y"])

In [ ]:
# I not want to split the data into two based off high or low gdp