In [1]:
import pandas as pd

In [3]:
countries = pd.read_csv("CountriesSD.csv")
summer = pd.read_csv("SummerSD.csv")
winter = pd.read_csv("WinterSD.csv")

In [5]:
#clean any missing values from each dataset
countries.dropna()

     Unnamed: 0              Country Code  Population  GDP per Capita
0             0          Afghanistan  AFG  32526562.0      594.323081
1             1              Albania  ALB   2889167.0     3945.217582
2             2              Algeria  ALG  39666519.0     4206.031232
5             5               Angola  ANG  25021974.0     4101.472152
6             6  Antigua and Barbuda  ANT     91818.0    13714.731962
..          ...                  ...  ...         ...             ...
194         194              Vanuatu  VAN    264652.0     2805.314644
196         196              Vietnam  VIE  91703800.0     2111.138024
198         198                Yemen  YEM  26832215.0     1406.291651
199         199               Zambia  ZAM  16211767.0     1304.879014
200         200             Zimbabwe  ZIM  15602751.0      924.143819

[176 rows x 5 columns]

In [6]:
summer.dropna()

,Unnamed: 0,Year,City,Sport,Discipline,Athlete,Code,Gender,Event,Medal,Country
0,0,1896,Athens,Aquatics,Swimming,Alfred Hajos,HUN,Men,100M Freestyle,Gold,Hungary
1,1,1896,Athens,Aquatics,Swimming,Otto Herschmann,AUT,Men,100M Freestyle,Silver,Austria
2,2,1896,Athens,Aquatics,Swimming,Dimitrios Drivas,GRE,Men,100M Freestyle For Sailors,Bronze,Greece
3,3,1896,Athens,Aquatics,Swimming,Ioannis Malokinis,GRE,Men,100M Freestyle For Sailors,Gold,Greece
4,4,1896,Athens,Aquatics,Swimming,Spiridon Chasapis,GRE,Men,100M Freestyle For Sailors,Silver,Greece
...,...,...,...,...,...,...,...,...,...,...,...
31160,31160,2012,London,Wrestling,Wrestling Freestyle,Damian Janikowski,POL,Men,Wg 84 KG,Bronze,Poland
31161,31161,2012,London,Wrestling,Wrestling Freestyle,Ghasem Gholamreza Rezaei,IRI,Men,Wg 96 KG,Gold,Iran
31162,31162,2012,London,Wrestling,Wrestling Freestyle,Rustam Totrov,RUS,Men,Wg 96 KG,Silver,Russia
31163,31163,2012,London,Wrestling,Wrestling Freestyle,Artur Aleksanyan,ARM,Men,Wg 96 KG,Bronze,Armenia
31164,31164,2012,London,Wrestling,Wrestling Freestyle,Jimmy Lidberg,SWE,Men,Wg 96 KG,Bronze,Sweden

In [7]:
winter.dropna()

,Unnamed: 0,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,0,1924,Chamonix,Biathlon,Biathlon,"BERTHET, G.",FRA,Men,Military Patrol,Bronze
1,1,1924,Chamonix,Biathlon,Biathlon,"MANDRILLON, C.",FRA,Men,Military Patrol,Bronze
2,2,1924,Chamonix,Biathlon,Biathlon,"MANDRILLON, Maurice",FRA,Men,Military Patrol,Bronze
3,3,1924,Chamonix,Biathlon,Biathlon,"VANDELLE, André",FRA,Men,Military Patrol,Bronze
4,4,1924,Chamonix,Biathlon,Biathlon,"AUFDENBLATTEN, Adolf",SUI,Men,Military Patrol,Gold
...,...,...,...,...,...,...,...,...,...,...
5765,5765,2014,Sochi,Skiing,Snowboard,"JONES, Jenny",GBR,Women,Slopestyle,Bronze
5766,5766,2014,Sochi,Skiing,Snowboard,"ANDERSON, Jamie",USA,Women,Slopestyle,Gold
5767,5767,2014,Sochi,Skiing,Snowboard,"MALTAIS, Dominique",CAN,Women,Snowboard Cross,Silver
5768,5768,2014,Sochi,Skiing,Snowboard,"SAMKOVA, Eva",CZE,Women,Snowboard Cross,Gold
5769,5769,2014,Sochi,Skiing,Snowboard,"TRESPEUCH, Chloe",FRA,Women,Snowboard Cross,Bronze

In [ ]:
# for each country now lets split the data up between men and women and then fort in descending order to get the most recent games for each. 
summer_male_olympians = summer[summer['Gender'] == 'Men']
summer_female_olympians = summer[summer['Gender'] == 'Women']

summer_male_olympians.sort_values(by='Year', ascending=False).head(15)

,Unnamed: 0,Year,City,Sport,Discipline,Athlete,Code,Gender,Event,Medal,Country
31164,31164,2012,London,Wrestling,Wrestling Freestyle,Jimmy Lidberg,SWE,Men,Wg 96 KG,Bronze,Sweden
29761,29761,2012,London,Athletics,Athletics,David Storl,GER,Men,Shot Put,Silver,Germany
29921,29921,2012,London,Canoe,Canoe Slalom,Sideris Tasiadis,GER,Men,C-1 (Single),Silver,Germany
29920,29920,2012,London,Canoe,Canoe Slalom,Tony Estanguet,FRA,Men,C-1 (Single),Gold,France
29919,29919,2012,London,Boxing,Boxing,Tervel Pulev,BUL,Men,81 - 91KG,Bronze,Bulgaria
29918,29918,2012,London,Boxing,Boxing,Teymur Mammadov,AZE,Men,81 - 91KG,Bronze,Azerbaijan
29917,29917,2012,London,Boxing,Boxing,Clemente Russo,ITA,Men,81 - 91KG,Silver,Italy
29916,29916,2012,London,Boxing,Boxing,Oleksandr Usyk,UKR,Men,81 - 91KG,Gold,Ukraine
29911,29911,2012,London,Boxing,Boxing,Oleksandr Gvozdyk,UKR,Men,75 - 81KG,Bronze,Ukraine
29910,29910,2012,London,Boxing,Boxing,Yamaguchi Falcao Florentino,BRA,Men,75 - 81KG,Bronze,Brazil
29909,29909,2012,London,Boxing,Boxing,Adilbek Niyazymbetov,KAZ,Men,75 - 81KG,Silver,Kazakhstan
29908,29908,2012,London,Boxing,Boxing,Egor Mekhontcev,RUS,Men,75 - 81KG,Gold,Russia
29907,29907,2012,London,Boxing,Boxing,Anthony Ogogo,GBR,Men,69 - 75 KG,Bronze,United Kingdom
29906,29906,2012,London,Boxing,Boxing,Abbos Atoev,UZB,Men,69 - 75 KG,Bronze,Uzbekistan
29905,29905,2012,London,Boxing,Boxing,Esquiva Falcao Florentino,BRA,Men,69 - 75 KG,Silver,Brazil

In [18]:
summer_female_olympians.sort_values(by='Year', ascending=False).head(15)

,Unnamed: 0,Year,City,Sport,Discipline,Athlete,Code,Gender,Event,Medal,Country
31124,31124,2012,London,Wrestling,Wrestling Freestyle,Maider Unda,ESP,Women,Wf 72 KG,Bronze,Spain
29841,29841,2012,London,Basketball,Basketball,Candace Parker,USA,Women,Basketball,Gold,United States
29839,29839,2012,London,Basketball,Basketball,Angel Mccoughtry,USA,Women,Basketball,Gold,United States
29838,29838,2012,London,Basketball,Basketball,Asjha Jones,USA,Women,Basketball,Gold,United States
29837,29837,2012,London,Basketball,Basketball,Sylvia Fowles,USA,Women,Basketball,Gold,United States
29836,29836,2012,London,Basketball,Basketball,Tina Charles,USA,Women,Basketball,Gold,United States
29835,29835,2012,London,Basketball,Basketball,Tamika Catchings,USA,Women,Basketball,Gold,United States
29834,29834,2012,London,Basketball,Basketball,Swin Cash,USA,Women,Basketball,Gold,United States
29833,29833,2012,London,Basketball,Basketball,Sue Bird,USA,Women,Basketball,Gold,United States
29832,29832,2012,London,Basketball,Basketball,Seimone Augustus,USA,Women,Basketball,Gold,United States
29795,29795,2012,London,Badminton,Badminton,Saina Nehwal,IND,Women,Singles,Bronze,India
29794,29794,2012,London,Badminton,Badminton,Yihan Wang,CHN,Women,Singles,Silver,China
29793,29793,2012,London,Badminton,Badminton,Xuerui Li,CHN,Women,Singles,Gold,China
29789,29789,2012,London,Badminton,Badminton,Christinna Pedersen,DEN,Women,Doubles,Bronze,Denmark
29786,29786,2012,London,Badminton,Badminton,Jin Ma,CHN,Women,Doubles,Silver,China